#!/usr/bin/env bash
# pin-images.sh - write images.env: every image of the store packages
# (Umbrel, CasaOS) as <exact tag>@<multi-arch index digest>, which store
# review requires. Run after a release build, then regenerate the packages:
#
#   deploy/compose/platforms/pin-images.sh 2610.8
#   deploy/compose/platforms/umbrel/build.sh && deploy/compose/platforms/casaos/build.sh
#
# The third-party tags are the exact releases the bundle's moving tags point
# at when this runs (mongo, mysql, redis and minio are pinned already).
# Needs docker buildx (imagetools) and network access; an image that cannot
# be resolved is written with @sha256:PENDING and the packages are not
# installable until it is pinned.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD="${1:?usage: pin-images.sh <release build, e.g. 2610.8>}"
[[ "$BUILD" =~ ^[0-9]{4}\.[0-9]+$ ]] || { echo "build must look like 2610.8" >&2; exit 2; }
CENTRIFUGO_TAG="${CENTRIFUGO_TAG:-v6.9.7}"   # what centrifugo/centrifugo:v6 is
CADDY_TAG="${CADDY_TAG:-2.10.2-alpine}"      # what caddy:2.10-alpine is

digest() {
  local d
  d="$(docker buildx imagetools inspect "$1" --format '{{.Manifest.Digest}}' 2>/dev/null | grep -E '^sha256:[0-9a-f]{64}$')" || true
  if [ -z "$d" ]; then echo "[pin] could not resolve $1; written as PENDING" >&2; d="sha256:PENDING"; fi
  echo "$1@$d"
}

{
  echo "# Image pins of the store packages (Umbrel, CasaOS). GENERATED by"
  echo "# pin-images.sh $BUILD on $(date -u +%Y-%m-%d); tag@digest, multi-arch index."
  echo "ETHORA_BUILD=$BUILD"
  echo "ETHORA_API_IMAGE=$(digest "docker.io/dappros/ethora-api:$BUILD")"
  echo "ETHORA_FRONTEND_IMAGE=$(digest "docker.io/dappros/ethora-frontend:$BUILD")"
  echo "ETHORA_XMPP_IMAGE=$(digest "docker.io/dappros/ethora-xmpp:$BUILD")"
  echo "ETHORA_COMPOSE_INIT_IMAGE=$(digest "docker.io/dappros/ethora-compose-init:$BUILD")"
  echo "MONGO_IMAGE=$(digest "docker.io/library/mongo:6.0.8")"
  echo "MYSQL_IMAGE=$(digest "docker.io/library/mysql:8.1.0")"
  echo "REDIS_IMAGE=$(digest "docker.io/library/redis:7.4-alpine")"
  echo "MINIO_IMAGE=$(digest "docker.io/dappros/minio:RELEASE.2025-09-07T16-13-09Z")"
  echo "CENTRIFUGO_IMAGE=$(digest "docker.io/centrifugo/centrifugo:$CENTRIFUGO_TAG")"
  echo "CADDY_IMAGE=$(digest "docker.io/library/caddy:$CADDY_TAG")"
} > "$HERE/images.env.tmp"
mv "$HERE/images.env.tmp" "$HERE/images.env"
cat "$HERE/images.env"
